### ISSUE TITLE
widevine-update no longer installs

### ISSUE THREAD

**Issue by akhepcat** [mrfixit2001/updates_repo#3]
Due to the method of testing in the $VER//filesystem/mrfixit_update.sh  script,  widevine-update does not install in any system past version 1.2 of the script.

Instead of being tied to the running version, the update script should check for the existence of /usr/bin/update_widevine.sh  and install if not present.     Same for the desktop shortcut.

**Comment by mrfixit2001** [comment]
Thanks for the note! The reasoning behind the current programming is because not all users want this link on their desktop. If a user updates from a version prior to the desktop shortcut's initial implementation (version 1.2), for example from version 1.1, then this desktop shortcut is added. If you already have a running version of 1.2 or higher then your release had this shortcut "out of the box". If you have removed the shortcut then I don't want the update script to re-add it. That would be very annoying for end-users to always have the same desktop shortcut being re-added after they purposely removed it.

Hope that makes sense! But this is by-design.
